// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3s103dEdobEjm5ZsiC0UxE8bqbmmQK7g',
    appId: '1:657681276345:android:2feeb86bff5704c7736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    databaseURL: 'https://forpartum-620c4-default-rtdb.firebaseio.com',
    storageBucket: 'forpartum-620c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV4OagFLRklsYP4uKUfwNfdokABTQTHw8',
    appId: '1:657681276345:ios:4320030bf46f9cd5736a68',
    messagingSenderId: '657681276345',
    projectId: 'forpartum-620c4',
    databaseURL: 'https://forpartum-620c4-default-rtdb.firebaseio.com',
    storageBucket: 'forpartum-620c4.appspot.com',
    androidClientId: '657681276345-02hjp3je9e4jdubaq9rrd2ajhrb9kodb.apps.googleusercontent.com',
    iosClientId: '657681276345-bsp13sdtqgdsbi946846gjorr9arnstk.apps.googleusercontent.com',
    iosBundleId: 'com.professional.propartum',
  );
}
